# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.7

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/bhagabot/dev/git/MayaLand/Engine

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/bhagabot/dev/git/MayaLand/Engine

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bhagabot/dev/git/MayaLand/Engine/CMakeFiles /home/bhagabot/dev/git/MayaLand/Engine/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bhagabot/dev/git/MayaLand/Engine/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named MayaLand

# Build rule for target.
MayaLand: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 MayaLand
.PHONY : MayaLand

# fast build rule for target.
MayaLand/fast:
	$(MAKE) -f CMakeFiles/MayaLand.dir/build.make CMakeFiles/MayaLand.dir/build
.PHONY : MayaLand/fast

src/ai/Block.o: src/ai/Block.cpp.o

.PHONY : src/ai/Block.o

# target to build an object file
src/ai/Block.cpp.o:
	$(MAKE) -f CMakeFiles/MayaLand.dir/build.make CMakeFiles/MayaLand.dir/src/ai/Block.cpp.o
.PHONY : src/ai/Block.cpp.o

src/ai/Block.i: src/ai/Block.cpp.i

.PHONY : src/ai/Block.i

# target to preprocess a source file
src/ai/Block.cpp.i:
	$(MAKE) -f CMakeFiles/MayaLand.dir/build.make CMakeFiles/MayaLand.dir/src/ai/Block.cpp.i
.PHONY : src/ai/Block.cpp.i

src/ai/Block.s: src/ai/Block.cpp.s

.PHONY : src/ai/Block.s

# target to generate assembly for a file
src/ai/Block.cpp.s:
	$(MAKE) -f CMakeFiles/MayaLand.dir/build.make CMakeFiles/MayaLand.dir/src/ai/Block.cpp.s
.PHONY : src/ai/Block.cpp.s

src/ai/Pathfinder.o: src/ai/Pathfinder.cpp.o

.PHONY : src/ai/Pathfinder.o

# target to build an object file
src/ai/Pathfinder.cpp.o:
	$(MAKE) -f CMakeFiles/MayaLand.dir/build.make CMakeFiles/MayaLand.dir/src/ai/Pathfinder.cpp.o
.PHONY : src/ai/Pathfinder.cpp.o

src/ai/Pathfinder.i: src/ai/Pathfinder.cpp.i

.PHONY : src/ai/Pathfinder.i

# target to preprocess a source file
src/ai/Pathfinder.cpp.i:
	$(MAKE) -f CMakeFiles/MayaLand.dir/build.make CMakeFiles/MayaLand.dir/src/ai/Pathfinder.cpp.i
.PHONY : src/ai/Pathfinder.cpp.i

src/ai/Pathfinder.s: src/ai/Pathfinder.cpp.s

.PHONY : src/ai/Pathfinder.s

# target to generate assembly for a file
src/ai/Pathfinder.cpp.s:
	$(MAKE) -f CMakeFiles/MayaLand.dir/build.make CMakeFiles/MayaLand.dir/src/ai/Pathfinder.cpp.s
.PHONY : src/ai/Pathfinder.cpp.s

src/game/Game.o: src/game/Game.cpp.o

.PHONY : src/game/Game.o

# target to build an object file
src/game/Game.cpp.o:
	$(MAKE) -f CMakeFiles/MayaLand.dir/build.make CMakeFiles/MayaLand.dir/src/game/Game.cpp.o
.PHONY : src/game/Game.cpp.o

src/game/Game.i: src/game/Game.cpp.i

.PHONY : src/game/Game.i

# target to preprocess a source file
src/game/Game.cpp.i:
	$(MAKE) -f CMakeFiles/MayaLand.dir/build.make CMakeFiles/MayaLand.dir/src/game/Game.cpp.i
.PHONY : src/game/Game.cpp.i

src/game/Game.s: src/game/Game.cpp.s

.PHONY : src/game/Game.s

# target to generate assembly for a file
src/game/Game.cpp.s:
	$(MAKE) -f CMakeFiles/MayaLand.dir/build.make CMakeFiles/MayaLand.dir/src/game/Game.cpp.s
.PHONY : src/game/Game.cpp.s

src/graphics/Point.o: src/graphics/Point.cpp.o

.PHONY : src/graphics/Point.o

# target to build an object file
src/graphics/Point.cpp.o:
	$(MAKE) -f CMakeFiles/MayaLand.dir/build.make CMakeFiles/MayaLand.dir/src/graphics/Point.cpp.o
.PHONY : src/graphics/Point.cpp.o

src/graphics/Point.i: src/graphics/Point.cpp.i

.PHONY : src/graphics/Point.i

# target to preprocess a source file
src/graphics/Point.cpp.i:
	$(MAKE) -f CMakeFiles/MayaLand.dir/build.make CMakeFiles/MayaLand.dir/src/graphics/Point.cpp.i
.PHONY : src/graphics/Point.cpp.i

src/graphics/Point.s: src/graphics/Point.cpp.s

.PHONY : src/graphics/Point.s

# target to generate assembly for a file
src/graphics/Point.cpp.s:
	$(MAKE) -f CMakeFiles/MayaLand.dir/build.make CMakeFiles/MayaLand.dir/src/graphics/Point.cpp.s
.PHONY : src/graphics/Point.cpp.s

src/graphics/Polygon.o: src/graphics/Polygon.cpp.o

.PHONY : src/graphics/Polygon.o

# target to build an object file
src/graphics/Polygon.cpp.o:
	$(MAKE) -f CMakeFiles/MayaLand.dir/build.make CMakeFiles/MayaLand.dir/src/graphics/Polygon.cpp.o
.PHONY : src/graphics/Polygon.cpp.o

src/graphics/Polygon.i: src/graphics/Polygon.cpp.i

.PHONY : src/graphics/Polygon.i

# target to preprocess a source file
src/graphics/Polygon.cpp.i:
	$(MAKE) -f CMakeFiles/MayaLand.dir/build.make CMakeFiles/MayaLand.dir/src/graphics/Polygon.cpp.i
.PHONY : src/graphics/Polygon.cpp.i

src/graphics/Polygon.s: src/graphics/Polygon.cpp.s

.PHONY : src/graphics/Polygon.s

# target to generate assembly for a file
src/graphics/Polygon.cpp.s:
	$(MAKE) -f CMakeFiles/MayaLand.dir/build.make CMakeFiles/MayaLand.dir/src/graphics/Polygon.cpp.s
.PHONY : src/graphics/Polygon.cpp.s

src/graphics/Triangle.o: src/graphics/Triangle.cpp.o

.PHONY : src/graphics/Triangle.o

# target to build an object file
src/graphics/Triangle.cpp.o:
	$(MAKE) -f CMakeFiles/MayaLand.dir/build.make CMakeFiles/MayaLand.dir/src/graphics/Triangle.cpp.o
.PHONY : src/graphics/Triangle.cpp.o

src/graphics/Triangle.i: src/graphics/Triangle.cpp.i

.PHONY : src/graphics/Triangle.i

# target to preprocess a source file
src/graphics/Triangle.cpp.i:
	$(MAKE) -f CMakeFiles/MayaLand.dir/build.make CMakeFiles/MayaLand.dir/src/graphics/Triangle.cpp.i
.PHONY : src/graphics/Triangle.cpp.i

src/graphics/Triangle.s: src/graphics/Triangle.cpp.s

.PHONY : src/graphics/Triangle.s

# target to generate assembly for a file
src/graphics/Triangle.cpp.s:
	$(MAKE) -f CMakeFiles/MayaLand.dir/build.make CMakeFiles/MayaLand.dir/src/graphics/Triangle.cpp.s
.PHONY : src/graphics/Triangle.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/MayaLand.dir/build.make CMakeFiles/MayaLand.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/MayaLand.dir/build.make CMakeFiles/MayaLand.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/MayaLand.dir/build.make CMakeFiles/MayaLand.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/math/Vector3.o: src/math/Vector3.cpp.o

.PHONY : src/math/Vector3.o

# target to build an object file
src/math/Vector3.cpp.o:
	$(MAKE) -f CMakeFiles/MayaLand.dir/build.make CMakeFiles/MayaLand.dir/src/math/Vector3.cpp.o
.PHONY : src/math/Vector3.cpp.o

src/math/Vector3.i: src/math/Vector3.cpp.i

.PHONY : src/math/Vector3.i

# target to preprocess a source file
src/math/Vector3.cpp.i:
	$(MAKE) -f CMakeFiles/MayaLand.dir/build.make CMakeFiles/MayaLand.dir/src/math/Vector3.cpp.i
.PHONY : src/math/Vector3.cpp.i

src/math/Vector3.s: src/math/Vector3.cpp.s

.PHONY : src/math/Vector3.s

# target to generate assembly for a file
src/math/Vector3.cpp.s:
	$(MAKE) -f CMakeFiles/MayaLand.dir/build.make CMakeFiles/MayaLand.dir/src/math/Vector3.cpp.s
.PHONY : src/math/Vector3.cpp.s

src/math/Vector3Util.o: src/math/Vector3Util.cpp.o

.PHONY : src/math/Vector3Util.o

# target to build an object file
src/math/Vector3Util.cpp.o:
	$(MAKE) -f CMakeFiles/MayaLand.dir/build.make CMakeFiles/MayaLand.dir/src/math/Vector3Util.cpp.o
.PHONY : src/math/Vector3Util.cpp.o

src/math/Vector3Util.i: src/math/Vector3Util.cpp.i

.PHONY : src/math/Vector3Util.i

# target to preprocess a source file
src/math/Vector3Util.cpp.i:
	$(MAKE) -f CMakeFiles/MayaLand.dir/build.make CMakeFiles/MayaLand.dir/src/math/Vector3Util.cpp.i
.PHONY : src/math/Vector3Util.cpp.i

src/math/Vector3Util.s: src/math/Vector3Util.cpp.s

.PHONY : src/math/Vector3Util.s

# target to generate assembly for a file
src/math/Vector3Util.cpp.s:
	$(MAKE) -f CMakeFiles/MayaLand.dir/build.make CMakeFiles/MayaLand.dir/src/math/Vector3Util.cpp.s
.PHONY : src/math/Vector3Util.cpp.s

src/resources/Conf.o: src/resources/Conf.cpp.o

.PHONY : src/resources/Conf.o

# target to build an object file
src/resources/Conf.cpp.o:
	$(MAKE) -f CMakeFiles/MayaLand.dir/build.make CMakeFiles/MayaLand.dir/src/resources/Conf.cpp.o
.PHONY : src/resources/Conf.cpp.o

src/resources/Conf.i: src/resources/Conf.cpp.i

.PHONY : src/resources/Conf.i

# target to preprocess a source file
src/resources/Conf.cpp.i:
	$(MAKE) -f CMakeFiles/MayaLand.dir/build.make CMakeFiles/MayaLand.dir/src/resources/Conf.cpp.i
.PHONY : src/resources/Conf.cpp.i

src/resources/Conf.s: src/resources/Conf.cpp.s

.PHONY : src/resources/Conf.s

# target to generate assembly for a file
src/resources/Conf.cpp.s:
	$(MAKE) -f CMakeFiles/MayaLand.dir/build.make CMakeFiles/MayaLand.dir/src/resources/Conf.cpp.s
.PHONY : src/resources/Conf.cpp.s

src/scene/Camera.o: src/scene/Camera.cpp.o

.PHONY : src/scene/Camera.o

# target to build an object file
src/scene/Camera.cpp.o:
	$(MAKE) -f CMakeFiles/MayaLand.dir/build.make CMakeFiles/MayaLand.dir/src/scene/Camera.cpp.o
.PHONY : src/scene/Camera.cpp.o

src/scene/Camera.i: src/scene/Camera.cpp.i

.PHONY : src/scene/Camera.i

# target to preprocess a source file
src/scene/Camera.cpp.i:
	$(MAKE) -f CMakeFiles/MayaLand.dir/build.make CMakeFiles/MayaLand.dir/src/scene/Camera.cpp.i
.PHONY : src/scene/Camera.cpp.i

src/scene/Camera.s: src/scene/Camera.cpp.s

.PHONY : src/scene/Camera.s

# target to generate assembly for a file
src/scene/Camera.cpp.s:
	$(MAKE) -f CMakeFiles/MayaLand.dir/build.make CMakeFiles/MayaLand.dir/src/scene/Camera.cpp.s
.PHONY : src/scene/Camera.cpp.s

src/scene/Light.o: src/scene/Light.cpp.o

.PHONY : src/scene/Light.o

# target to build an object file
src/scene/Light.cpp.o:
	$(MAKE) -f CMakeFiles/MayaLand.dir/build.make CMakeFiles/MayaLand.dir/src/scene/Light.cpp.o
.PHONY : src/scene/Light.cpp.o

src/scene/Light.i: src/scene/Light.cpp.i

.PHONY : src/scene/Light.i

# target to preprocess a source file
src/scene/Light.cpp.i:
	$(MAKE) -f CMakeFiles/MayaLand.dir/build.make CMakeFiles/MayaLand.dir/src/scene/Light.cpp.i
.PHONY : src/scene/Light.cpp.i

src/scene/Light.s: src/scene/Light.cpp.s

.PHONY : src/scene/Light.s

# target to generate assembly for a file
src/scene/Light.cpp.s:
	$(MAKE) -f CMakeFiles/MayaLand.dir/build.make CMakeFiles/MayaLand.dir/src/scene/Light.cpp.s
.PHONY : src/scene/Light.cpp.s

src/scene/Object.o: src/scene/Object.cpp.o

.PHONY : src/scene/Object.o

# target to build an object file
src/scene/Object.cpp.o:
	$(MAKE) -f CMakeFiles/MayaLand.dir/build.make CMakeFiles/MayaLand.dir/src/scene/Object.cpp.o
.PHONY : src/scene/Object.cpp.o

src/scene/Object.i: src/scene/Object.cpp.i

.PHONY : src/scene/Object.i

# target to preprocess a source file
src/scene/Object.cpp.i:
	$(MAKE) -f CMakeFiles/MayaLand.dir/build.make CMakeFiles/MayaLand.dir/src/scene/Object.cpp.i
.PHONY : src/scene/Object.cpp.i

src/scene/Object.s: src/scene/Object.cpp.s

.PHONY : src/scene/Object.s

# target to generate assembly for a file
src/scene/Object.cpp.s:
	$(MAKE) -f CMakeFiles/MayaLand.dir/build.make CMakeFiles/MayaLand.dir/src/scene/Object.cpp.s
.PHONY : src/scene/Object.cpp.s

src/scene/World.o: src/scene/World.cpp.o

.PHONY : src/scene/World.o

# target to build an object file
src/scene/World.cpp.o:
	$(MAKE) -f CMakeFiles/MayaLand.dir/build.make CMakeFiles/MayaLand.dir/src/scene/World.cpp.o
.PHONY : src/scene/World.cpp.o

src/scene/World.i: src/scene/World.cpp.i

.PHONY : src/scene/World.i

# target to preprocess a source file
src/scene/World.cpp.i:
	$(MAKE) -f CMakeFiles/MayaLand.dir/build.make CMakeFiles/MayaLand.dir/src/scene/World.cpp.i
.PHONY : src/scene/World.cpp.i

src/scene/World.s: src/scene/World.cpp.s

.PHONY : src/scene/World.s

# target to generate assembly for a file
src/scene/World.cpp.s:
	$(MAKE) -f CMakeFiles/MayaLand.dir/build.make CMakeFiles/MayaLand.dir/src/scene/World.cpp.s
.PHONY : src/scene/World.cpp.s

src/scene/object/DynamicObject.o: src/scene/object/DynamicObject.cpp.o

.PHONY : src/scene/object/DynamicObject.o

# target to build an object file
src/scene/object/DynamicObject.cpp.o:
	$(MAKE) -f CMakeFiles/MayaLand.dir/build.make CMakeFiles/MayaLand.dir/src/scene/object/DynamicObject.cpp.o
.PHONY : src/scene/object/DynamicObject.cpp.o

src/scene/object/DynamicObject.i: src/scene/object/DynamicObject.cpp.i

.PHONY : src/scene/object/DynamicObject.i

# target to preprocess a source file
src/scene/object/DynamicObject.cpp.i:
	$(MAKE) -f CMakeFiles/MayaLand.dir/build.make CMakeFiles/MayaLand.dir/src/scene/object/DynamicObject.cpp.i
.PHONY : src/scene/object/DynamicObject.cpp.i

src/scene/object/DynamicObject.s: src/scene/object/DynamicObject.cpp.s

.PHONY : src/scene/object/DynamicObject.s

# target to generate assembly for a file
src/scene/object/DynamicObject.cpp.s:
	$(MAKE) -f CMakeFiles/MayaLand.dir/build.make CMakeFiles/MayaLand.dir/src/scene/object/DynamicObject.cpp.s
.PHONY : src/scene/object/DynamicObject.cpp.s

src/scene/object/StaticObject.o: src/scene/object/StaticObject.cpp.o

.PHONY : src/scene/object/StaticObject.o

# target to build an object file
src/scene/object/StaticObject.cpp.o:
	$(MAKE) -f CMakeFiles/MayaLand.dir/build.make CMakeFiles/MayaLand.dir/src/scene/object/StaticObject.cpp.o
.PHONY : src/scene/object/StaticObject.cpp.o

src/scene/object/StaticObject.i: src/scene/object/StaticObject.cpp.i

.PHONY : src/scene/object/StaticObject.i

# target to preprocess a source file
src/scene/object/StaticObject.cpp.i:
	$(MAKE) -f CMakeFiles/MayaLand.dir/build.make CMakeFiles/MayaLand.dir/src/scene/object/StaticObject.cpp.i
.PHONY : src/scene/object/StaticObject.cpp.i

src/scene/object/StaticObject.s: src/scene/object/StaticObject.cpp.s

.PHONY : src/scene/object/StaticObject.s

# target to generate assembly for a file
src/scene/object/StaticObject.cpp.s:
	$(MAKE) -f CMakeFiles/MayaLand.dir/build.make CMakeFiles/MayaLand.dir/src/scene/object/StaticObject.cpp.s
.PHONY : src/scene/object/StaticObject.cpp.s

src/scene/object/dynamicObject/Enemy.o: src/scene/object/dynamicObject/Enemy.cpp.o

.PHONY : src/scene/object/dynamicObject/Enemy.o

# target to build an object file
src/scene/object/dynamicObject/Enemy.cpp.o:
	$(MAKE) -f CMakeFiles/MayaLand.dir/build.make CMakeFiles/MayaLand.dir/src/scene/object/dynamicObject/Enemy.cpp.o
.PHONY : src/scene/object/dynamicObject/Enemy.cpp.o

src/scene/object/dynamicObject/Enemy.i: src/scene/object/dynamicObject/Enemy.cpp.i

.PHONY : src/scene/object/dynamicObject/Enemy.i

# target to preprocess a source file
src/scene/object/dynamicObject/Enemy.cpp.i:
	$(MAKE) -f CMakeFiles/MayaLand.dir/build.make CMakeFiles/MayaLand.dir/src/scene/object/dynamicObject/Enemy.cpp.i
.PHONY : src/scene/object/dynamicObject/Enemy.cpp.i

src/scene/object/dynamicObject/Enemy.s: src/scene/object/dynamicObject/Enemy.cpp.s

.PHONY : src/scene/object/dynamicObject/Enemy.s

# target to generate assembly for a file
src/scene/object/dynamicObject/Enemy.cpp.s:
	$(MAKE) -f CMakeFiles/MayaLand.dir/build.make CMakeFiles/MayaLand.dir/src/scene/object/dynamicObject/Enemy.cpp.s
.PHONY : src/scene/object/dynamicObject/Enemy.cpp.s

src/scene/object/dynamicObject/Player.o: src/scene/object/dynamicObject/Player.cpp.o

.PHONY : src/scene/object/dynamicObject/Player.o

# target to build an object file
src/scene/object/dynamicObject/Player.cpp.o:
	$(MAKE) -f CMakeFiles/MayaLand.dir/build.make CMakeFiles/MayaLand.dir/src/scene/object/dynamicObject/Player.cpp.o
.PHONY : src/scene/object/dynamicObject/Player.cpp.o

src/scene/object/dynamicObject/Player.i: src/scene/object/dynamicObject/Player.cpp.i

.PHONY : src/scene/object/dynamicObject/Player.i

# target to preprocess a source file
src/scene/object/dynamicObject/Player.cpp.i:
	$(MAKE) -f CMakeFiles/MayaLand.dir/build.make CMakeFiles/MayaLand.dir/src/scene/object/dynamicObject/Player.cpp.i
.PHONY : src/scene/object/dynamicObject/Player.cpp.i

src/scene/object/dynamicObject/Player.s: src/scene/object/dynamicObject/Player.cpp.s

.PHONY : src/scene/object/dynamicObject/Player.s

# target to generate assembly for a file
src/scene/object/dynamicObject/Player.cpp.s:
	$(MAKE) -f CMakeFiles/MayaLand.dir/build.make CMakeFiles/MayaLand.dir/src/scene/object/dynamicObject/Player.cpp.s
.PHONY : src/scene/object/dynamicObject/Player.cpp.s

src/scene/object/staticObject/Tile.o: src/scene/object/staticObject/Tile.cpp.o

.PHONY : src/scene/object/staticObject/Tile.o

# target to build an object file
src/scene/object/staticObject/Tile.cpp.o:
	$(MAKE) -f CMakeFiles/MayaLand.dir/build.make CMakeFiles/MayaLand.dir/src/scene/object/staticObject/Tile.cpp.o
.PHONY : src/scene/object/staticObject/Tile.cpp.o

src/scene/object/staticObject/Tile.i: src/scene/object/staticObject/Tile.cpp.i

.PHONY : src/scene/object/staticObject/Tile.i

# target to preprocess a source file
src/scene/object/staticObject/Tile.cpp.i:
	$(MAKE) -f CMakeFiles/MayaLand.dir/build.make CMakeFiles/MayaLand.dir/src/scene/object/staticObject/Tile.cpp.i
.PHONY : src/scene/object/staticObject/Tile.cpp.i

src/scene/object/staticObject/Tile.s: src/scene/object/staticObject/Tile.cpp.s

.PHONY : src/scene/object/staticObject/Tile.s

# target to generate assembly for a file
src/scene/object/staticObject/Tile.cpp.s:
	$(MAKE) -f CMakeFiles/MayaLand.dir/build.make CMakeFiles/MayaLand.dir/src/scene/object/staticObject/Tile.cpp.s
.PHONY : src/scene/object/staticObject/Tile.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... MayaLand"
	@echo "... src/ai/Block.o"
	@echo "... src/ai/Block.i"
	@echo "... src/ai/Block.s"
	@echo "... src/ai/Pathfinder.o"
	@echo "... src/ai/Pathfinder.i"
	@echo "... src/ai/Pathfinder.s"
	@echo "... src/game/Game.o"
	@echo "... src/game/Game.i"
	@echo "... src/game/Game.s"
	@echo "... src/graphics/Point.o"
	@echo "... src/graphics/Point.i"
	@echo "... src/graphics/Point.s"
	@echo "... src/graphics/Polygon.o"
	@echo "... src/graphics/Polygon.i"
	@echo "... src/graphics/Polygon.s"
	@echo "... src/graphics/Triangle.o"
	@echo "... src/graphics/Triangle.i"
	@echo "... src/graphics/Triangle.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/math/Vector3.o"
	@echo "... src/math/Vector3.i"
	@echo "... src/math/Vector3.s"
	@echo "... src/math/Vector3Util.o"
	@echo "... src/math/Vector3Util.i"
	@echo "... src/math/Vector3Util.s"
	@echo "... src/resources/Conf.o"
	@echo "... src/resources/Conf.i"
	@echo "... src/resources/Conf.s"
	@echo "... src/scene/Camera.o"
	@echo "... src/scene/Camera.i"
	@echo "... src/scene/Camera.s"
	@echo "... src/scene/Light.o"
	@echo "... src/scene/Light.i"
	@echo "... src/scene/Light.s"
	@echo "... src/scene/Object.o"
	@echo "... src/scene/Object.i"
	@echo "... src/scene/Object.s"
	@echo "... src/scene/World.o"
	@echo "... src/scene/World.i"
	@echo "... src/scene/World.s"
	@echo "... src/scene/object/DynamicObject.o"
	@echo "... src/scene/object/DynamicObject.i"
	@echo "... src/scene/object/DynamicObject.s"
	@echo "... src/scene/object/StaticObject.o"
	@echo "... src/scene/object/StaticObject.i"
	@echo "... src/scene/object/StaticObject.s"
	@echo "... src/scene/object/dynamicObject/Enemy.o"
	@echo "... src/scene/object/dynamicObject/Enemy.i"
	@echo "... src/scene/object/dynamicObject/Enemy.s"
	@echo "... src/scene/object/dynamicObject/Player.o"
	@echo "... src/scene/object/dynamicObject/Player.i"
	@echo "... src/scene/object/dynamicObject/Player.s"
	@echo "... src/scene/object/staticObject/Tile.o"
	@echo "... src/scene/object/staticObject/Tile.i"
	@echo "... src/scene/object/staticObject/Tile.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

